# #############################
# Country definition for UPS #
# #############################

province = { id = 1737 naval_base = 10 air_base = 10 anti_air = 4 } # Maui
province = { id = 1739 air_base = 5 anti_air = 3 } # Midway Island
province = { id = 1184 air_base = 2 naval_base = 2 anti_air = 1 } # Petropavlovsk-Kamchatskij
province = {
	id = 1541
	anti_air = 2
	naval_base = { size = 3 current_size = 3 }
	air_base = 1
} # Ocha
province = {
	id = 1547
	anti_air = 2
	air_base = { size = 10 current_size = 10 }
	naval_base = { size = 10 current_size = 10 }
} # Akita
province = { id = 1549 anti_air = 2 } # Fukushima
province = {
	id = 1552
	anti_air = 2
	air_base = { size = 10 current_size = 10 }
	naval_base = { size = 10 current_size = 10 }
} # Tokyo
province = {
	id = 1557
	anti_air = 2
	air_base = { size = 10 current_size = 10 }
	naval_base = { size = 10 current_size = 10 }
} # Nagoya
province = {
	id = 1556
	anti_air = 2
	air_base = { size = 10 current_size = 10 }
	naval_base = { size = 10 current_size = 10 }
} # Kanazawa
province = {
	id = 1553
	anti_air = 2
	air_base = { size = 10 current_size = 10 }
	naval_base = { size = 10 current_size = 10 }
} # Osaka
province = {
	id = 1554
	anti_air = 4
	air_base = { size = 10 current_size = 10 }
	naval_base = { size = 10 current_size = 10 }
} # Hiroshima
province = {
	id = 1559
	anti_air = 2
	air_base = { size = 10 current_size = 10 }
	naval_base = { size = 10 current_size = 10 }
} # Shikoku
province = {
	id = 1560
	anti_air = 2
	air_base = { size = 10 current_size = 10 }
	naval_base = { size = 10 current_size = 10 }
} # Fukuoka
province = {
	id = 1563
	anti_air = 2
	air_base = { size = 6 current_size = 6 }
	naval_base = { size = 6 current_size = 6 }
	supplypool = 1000
} # Okinawa
province = {
	id = 1232
	anti_air = 2
	air_base = { size = 10 current_size = 10 }
	naval_base = { size = 10 current_size = 10 }
	supplypool = 5000
	oilpool = 100
} # Busan
province = {
	id = 1220
	anti_air = 4
	naval_base = { size = 5 current_size = 5 }
	air_base = { size = 7 current_size = 7 }
	supplypool = 500
	oilpool = 100
} # Dalian
province = {
	id = 1245
	supplypool = 1000
	oilpool = 100
} # Tangshan
province = {
	id = 1361
	anti_air = 2
	air_base = { size = 8 current_size = 8 }
	naval_base = { size = 10 current_size = 10 }
	supplypool = 1000
	oilpool = 100
} # Kaohsiung
province = { id = 1362  anti_air = 2 } # Taipei
province = {
	id = 1185
	air_base = { size = 1 current_size = 1 }
	anti_air = 1
} # Komsomolsk-na-Amure
province = { id = 1195 naval_base = 5 air_base = 5 anti_air = 2 } # Tetyukhe
province = { id = 1199 air_base = 5 anti_air = 1 } # Harbin
province = { id = 1207 anti_air = 1 } # Xinjing
province = {
	id = 1226
	anti_air = 2
	air_base = { size = 4 current_size = 4 }
} # Hyesan
province = {
	id = 1310
	anti_air = 2
	air_base = { size = 2 current_size = 2 }
} # Changde
province = {
	id = 1661
	supplypool = 500
} # Iwo Jima
province = {
	id = 1675
	anti_air = 5
	air_base = { size = 4 current_size = 4 }
	naval_base = { size = 2 current_size = 2 }
	supplypool = 500
} # Eniwetok
province = { id = 1668 air_base = 1 anti_air = 1 } # Wolelai
province = { id = 1677 anti_air = 3 } # Majuro
province = {
	id = 1676
	anti_air = 5
	air_base = { size = 4 current_size = 4 }
	naval_base = { size = 2 current_size = 2 }
	supplypool = 2000
} # Kwajalein
province = {
	id = 1665
	supplypool = 500
	naval_base = 3
	air_base = 2
	anti_air = 1
} # Ponape
province = {
	id = 1667
	anti_air = 5
	air_base = { size = 10 current_size = 10 }
	naval_base = { size = 10 current_size = 10 }
	supplypool = 500
} # Truk
province = {
	id = 1668
	supplypool = 500
} # Ulithi
province = {
	id = 1669
	anti_air = 3
	supplypool = 500
} # Yap
province = {
	id = 1670
	supplypool = 500
	air_base = 2
	anti_air = 1
} # Palau
province = { id = 1683 air_base = 2 anti_air = 1 } # Guam
province = {
	id = 1684
	supplypool = 500
} # Rota
province = {
	id = 1685
	supplypool = 500
} # Tinian
province = {
	id = 1686
	anti_air = 3
	supplypool = 500
	naval_base = 6
	air_base = 6
} # Saipan
province = { id = 1628 air_base = 6 anti_air = 2 } # Semitau
province = { id = 1626 naval_base = 4 air_base = 3 anti_air = 2 } # Jesselton
province = { id = 1660 air_base = 8 anti_air = 3 } # Palu
province = { id = 1570 naval_base = 5 air_base = 3 anti_air = 2 } # Aparri
province = { id = 1565 air_base = 8 anti_air = 2 } # Lamon Bay
province = { id = 1578 naval_base = 1 air_base = 4 anti_air = 1 } # Cagayan
province = { id = 1662 anti_air = 2 } # Bonin Islands
province = {
	id = 1672
	supplypool = 500
} # Marcus Island
province = { id = 1673 naval_base = 7 anti_air = 2 } # Wake Island


# ####################
# Country main data #
# ####################

country = {
	tag = UPS
	ai = "JAP.ai"
	capital = 1552
	belligerence = 50
	manpower = 1000
	# Resource Reserves
	energy = 1000
	metal = 1000
	rare_materials = 500
	oil = 500
	supplies = 500
	money = 100
	transports = 500
	escorts = 100
	policy = {
		date = { year = 0 month = january day = 0 }
		democratic = 1
		political_left = 10
		freedom = 6
		free_market = 6
		professional_army = 6
		defense_lobby = 6
		interventionism = 10
	}
	diplomacy = { }
	
	#nationalprovinces = {
	#	1120 1161 1168 1170 1174 1175 1176 1182 1183 1184 1185 1187 1188 1189 1190 1191 1192 1193 1194 1195 1196 1197
	#	1198 1199 1200 1201 1202 1203 1204 1205 1206 1207 1208 1209 1210 1211 1212 1213 1214 1215 1216 1217 1218 1219
	#	1220 1221 1222 1223 1224 1225 1226 1227 1228 1229 1230 1231 1232 1233 1235 1236 1237 1239 1240 1241 1245 1246
	#	1247 1310 1361 1362 1363 1364 1432 1541 1542 1543 1544 1545 1546 1547 1548 1549 1550 1551 1552 1553 1554 1555
	#	1556 1557 1558 1559 1560 1561 1562 1563 1564 1565 1566 1567 1568 1569 1570 1571 1572 1573 1574 1575 1576 1577
	#	1578 1579 1580 1615 1619 1620 1621 1623 1624 1625 1626 1627 1628 1629 1630 1631 1632 1633 1639 1643 1644 1647
	#	1648 1649 1650 1652 1653 1656 1657 1658 1659 1660 1661 1662 1663 1664 1665 1666 1667 1668 1669 1670 1671 1672
	#	1673 1674 1675 1676 1677 1681 1683 1684 1685 1686 1734 1735 1736 1737 1738 1739
	#}
	nationalprovinces = {
		1183 1184 1185 1187 1190 1191 1192 1193 1194 1195 1196 1197 1198 1199 1200 1201 1202 1203 1204 1205 1206 1207
		1208 1209 1210 1211 1212 1213 1214 1215 1216 1217 1218 1219 1220 1221 1222 1223 1224 1225 1226 1227 1228 1229
		1230 1231 1232 1233 1235 1236 1237 1240 1245 1361 1362 1363 1364 1541 1542 1543 1544 1545 1546 1547 1548 1549
		1550 1551 1552 1553 1554 1555 1556 1557 1558 1559 1560 1561 1562 1563 1564 1565 1566 1567 1568 1569 1570 1571
		1572 1573 1574 1575 1576 1577 1578 1579 1580 1623 1624 1625 1626 1627 1628 1629 1630 1631 1632 1633 1657 1658
		1659 1660 1661 1662 1663 1664 1665 1666 1667 1668 1669 1670 1671 1672 1673 1674 1675 1676 1677 1681 1683 1684
		1685 1686 1734 1735 1736 1737 1738 1739
		
		1182 1181 1189 1188 1175 1174 1176 1170 1168 1120 1122 1239 1246 1247 1241 1432 1639 1648 1647 1649 1650 1652 1653 1656 1643 1644 1615 1619 1621 1620
	}
	
	ownedprovinces = {
		1183 1184 1185 1190 1191 1192 1193 1194 1195 1196 1197 1198 1199 1200 1201 1202 1203 1204 1205 1206 1207
		1208 1209 1210 1211 1212 1213 1214 1215 1216 1217 1218 1219 1220 1221 1222 1223 1224 1225 1226 1227 1228 1229
		1230 1231 1232 1233 1235 1236 1237 1240 1245 1361 1362 1363 1364 1541 1542 1543 1544 1545 1546 1547 1548 1549
		1550 1551 1552 1553 1554 1555 1556 1557 1558 1559 1560 1561 1562 1563 1564 1565 1566 1567 1568 1569 1570 1571
		1572 1573 1574 1575 1576 1577 1578 1579 1580 1623 1624 1625 1626 1627 1628 1629 1630 1631 1632 1633 1657 1658
		1659 1660 1661 1662 1663 1664 1665 1666 1667 1668 1669 1670 1671 1672 1673 1674 1675 1676 1677 1681 1683 1684
		1685 1686 1734 1735 1736 1737 1738 1739
	}
	
	controlledprovinces = {
		1183 1184 1185 1190 1191 1192 1193 1194 1195 1196 1197 1198 1199 1200 1201 1202 1203 1204 1205 1206 1207
		1208 1209 1210 1211 1212 1213 1214 1215 1216 1217 1218 1219 1220 1221 1222 1223 1224 1225 1226 1227 1228 1229
		1230 1231 1232 1233 1235 1236 1237 1240 1245 1361 1362 1363 1364 1541 1542 1543 1544 1545 1546 1547 1548 1549
		1550 1551 1552 1553 1554 1555 1556 1557 1558 1559 1560 1561 1562 1563 1564 1565 1566 1567 1568 1569 1570 1571
		1572 1573 1574 1575 1576 1577 1578 1579 1580 1623 1624 1625 1626 1627 1628 1629 1630 1631 1632 1633 1657 1658
		1659 1660 1661 1662 1663 1664 1665 1666 1667 1668 1669 1670 1671 1672 1673 1674 1675 1676 1677 1681 1683 1684
		1685 1686 1734 1735 1736 1737 1738 1739
	}
	
	# ######################
	techapps = {
		#Infantry up to 1918 tech
		1010 1020 1030 1040 1050 1060
		#Cavalry up to 1918 tech
		13060 13070 13080 1310 1320 1330
		#Mountain up to 1918 tech
		1160 1170 1180 1190 1200 1210
		#Engineers up to 1918 tech
		1830 1840 
		#Logistics up to 1918 tech
		1910 1920 1930 1940 1950 1960
		
		#Tanks up to 1918 tech
		2620 2010 
		#Armoured Cars up to 1918 tech
		2860 2870 
		#Artillery up to 1918 tech
		2290 2300 2310 2900
		#Static Anti-Air Artillery up to 1918 tech
		2800
		#Anti-Air Artillery Brigade up to 1918 tech
		2810

		#Destroyers up to 1918 tech
		3010 3020 3030 3040 
		#Light Cruisers up to 1918 tech
		3110 3120 3130
		#Heavy Cruiser up to 1918 tech 
		3210 3220 3230
		#Battleship up to 1918 tech
		3410 3420 3430 3440 3450 3456
		#Battlecruiser up to 1918 tech
		3310 3320 3330
		#Submarine up to 1918 tech
		3610 3620 3630 
		#Light carrier up to 1918 tech
		12100 12110
		#Troopships up to 1918 tech
		3810
		#ASW up to 1918 tech
		3900
		#Torpedoes up to 1918 tech
		3720 3730 3736 3740
		
		#Interceptors up to 1918 tech
		4500 4510 4520 4530 4540 4550
		#Multirole fighter up to 1918 tech
		4300 4310 4320 
		#Bombers up to 1918 tech
		4600 4610 4620 4630
		#Strategic bomber up to 1918 tech
		4800 4810
		#Navalbomber up to 1918 tech
		4700
		#Seaplanes up to 1918 tech
		4740 4750 4760
		
		#Computers up to 1918 tech
		5310 54010 54020 
		#Cryptography up to 1918 tech
		5316
		#Medicine up to 1918 tech
		5600 5610
		#Agriculture up to 1918 tech
		5700 5710 
		#Construction Engineering up to 1918 tech
		5800 5080
		#Manufacturing up to 1918 tech
		5810 5820
		#Oil Refining up to 1918 tech
		5190 

		#Hospitals up to 1918 tech
		14000 14010
		#Landdoctrine ww1 - entente line, up to 1926
		6500 6510 6530 6580 6600 6610 6680 6620 6630 6640 6650 6660 6670 6540 6910
		
		#Naval Doctrines
		# Theories
		8010 8020 8040 8050 8060 8070 8080
		# Amphib
		82300
		# Logistic Support
		82500
		# Naval Interdiction
		8500 8510 8520 8550 8560 8600 8610
		# Engagement Tactics
		8900 8910 8920 8930
		# Naval Supremacy
		8100 8110 8120 8150 8160 8200 8210

		#Air Doctrines - interwar techs
		27480 27490 27500 27510 27520 27530 27540 27550 27570 27580 27590 27600 9030 9020 27560 27460 27470
		
		#Secret weapons (tanks)
		7600 7610
	}
	
	landunit = {
		id = { type = 30018 id = 1 }
		name = "1. Corps"
		location = 1552
		division = {
			id = { type = 30018 id = 2 }
			name = "1st Infantry Division"
			strength = 100
			type = infantry
			model = 5
		}
		division = {
			id = { type = 30018 id = 3 }
			name = "2nd Infantry Division"
			strength = 100
			type = infantry
			model = 5
		}
		division = {
			id = { type = 30018 id = 4 }
			name = "3rd Infantry Division"
			strength = 100
			type = infantry
			model = 5
		}
	}
	landunit = {
		id = { type = 30018 id = 5 }
		name = "2. Corps"
		location = 1552
		division = {
			id = { type = 30018 id = 6 }
			name = "4th Infantry Division"
			strength = 100
			type = infantry
			model = 5
		}
		division = {
			id = { type = 30018 id = 7 }
			name = "5th Infantry Division"
			strength = 100
			type = infantry
			model = 5
		}
		division = {
			id = { type = 30018 id = 8 }
			name = "6th Infantry Division"
			strength = 100
			type = infantry
			model = 5
		}
	}
	landunit = {
		id = { type = 30018 id = 9 }
		name = "3. Corps"
		location = 1552
		division = {
			id = { type = 30018 id = 10 }
			name = "7th Infantry Division"
			strength = 100
			type = infantry
			model = 5
		}
		division = {
			id = { type = 30018 id = 11 }
			name = "8th Infantry Division"
			strength = 100
			type = infantry
			model = 5
		}
		division = {
			id = { type = 30018 id = 12 }
			name = "9th Infantry Division"
			strength = 100
			type = infantry
			model = 5
		}
	}
	landunit = {
		id = { type = 30018 id = 13 }
		name = "4. Corps"
		location = 1552
		division = {
			id = { type = 30018 id = 14 }
			name = "10th Infantry Division"
			strength = 100
			type = infantry
			model = 5
		}
		division = {
			id = { type = 30018 id = 15 }
			name = "11th Infantry Division"
			strength = 100
			type = infantry
			model = 5
		}
		division = {
			id = { type = 30018 id = 16 }
			name = "12th Infantry Division"
			strength = 100
			type = infantry
			model = 5
		}
	}
	landunit = {
		id = { type = 30018 id = 17 }
		name = "Armored Corps"
		location = 1552
		division = {
			type = light_armor
			model = 0
			id = { type = 30018 id = 18 }
			name = "1st Armored Division"
		}
		division = {
			type = light_armor
			model = 0
			id = { type = 30018 id = 19 }
			name = "2nd Armored Division"
		}
		division = {
			type = light_armor
			model = 0
			id = { type = 30018 id = 20 }
			name = "3rd Armored Division"
		}
	}
	navalunit = {
		id = { type = 30018 id = 393 }
		name = "Main Fleet"
		location = 1552
		base = 1552
		division = {
			type = carrier
			model = 0
			id = { type = 30018 id = 394 }
			name = "Carrier 1"
			extra = cag
			brigade_model = 0
		}
		division = {
			type = carrier
			model = 0
			id = { type = 30018 id = 395 }
			name = "Carrier 2"
			extra = cag
			brigade_model = 0
		}
		division = {
			type = battleship
			model = 4
			id = { type = 30018 id = 396 }
			name = "Battleship 1"
		}
		division = {
			type = battleship
			model = 4
			id = { type = 30018 id = 397 }
			name = "Battleship 2"
		}
		division = {
			type = battlecruiser
			model = 2
			id = { type = 30018 id = 398 }
			name = "Battlecruiser 1"
		}
		division = {
			type = battlecruiser
			model = 2
			id = { type = 30018 id = 399 }
			name = "Battlecruiser 2"
		}
		division = {
			type = heavy_cruiser
			model = 3
			id = { type = 30018 id = 300 }
			name = "Heavy Cruiser 1"
		}
		division = {
			type = heavy_cruiser
			model = 3
			id = { type = 30018 id = 301 }
			name = "Heavy Cruiser 2"
		}
		division = {
			type = light_cruiser
			model = 3
			id = { type = 30018 id = 302 }
			name = "Light Cruiser 1"
		}
		division = {
			type = light_cruiser
			model = 3
			id = { type = 30018 id = 303 }
			name = "Light Cruiser 2"
		}
		division = {
			type = light_cruiser
			model = 3
			id = { type = 30018 id = 304 }
			name = "Light Cruiser 3"
		}
		division = {
			type = light_cruiser
			model = 3
			id = { type = 30018 id = 305 }
			name = "Light Cruiser 4"
		}
		division = {
			type = destroyer
			model = 3
			id = { type = 30018 id = 306 }
			name = "Destroyer 1"
		}
		division = {
			type = destroyer
			model = 3
			id = { type = 30018 id = 307 }
			name = "Destroyer 2"
		}
		division = {
			type = destroyer
			model = 3
			id = { type = 30018 id = 308 }
			name = "Destroyer 3"
		}
		division = {
			type = destroyer
			model = 3
			id = { type = 30018 id = 309 }
			name = "Destroyer 4"
		}
		division = {
			type = destroyer
			model = 3
			id = { type = 30018 id = 310 }
			name = "Destroyer 5"
		}
		division = {
			type = destroyer
			model = 3
			id = { type = 30018 id = 311 }
			name = "Destroyer 6"
		}
		division = {
			type = transport
			model = 3
			id = { type = 30018 id = 312 }
			name = "Transport 1"
		}
		division = {
			type = transport
			model = 3
			id = { type = 30018 id = 313 }
			name = "Transport 2"
		}
		division = {
			type = submarine
			model = 1
			id = { type = 30018 id = 314 }
			name = "Submarine 1"
		}
		division = {
			type = submarine
			model = 1
			id = { type = 30018 id = 315 }
			name = "Submarine 2"
		}
		division = {
			type = submarine
			model = 1
			id = { type = 30018 id = 316 }
			name = "Submarine 3"
		}
		division = {
			type = submarine
			model = 1
			id = { type = 30018 id = 317 }
			name = "Submarine 4"
		}
	}
	airunit = {
		id = { type = 30018 id = 373 }
		name = "Bomber Group 1"
		location = 1552
		base = 1552
		division = {
			type = tactical_bomber
			model = 4
			id = { type = 30018 id = 374 }
			name = "1st Air Wing"
		}
		division = {
			type = tactical_bomber
			model = 4
			id = { type = 30018 id = 375 }
			name = "2nd Air Wing"
		}
		division = {
			type = tactical_bomber
			model = 4
			id = { type = 30018 id = 376 }
			name = "3rd Air Wing"
		}
		division = {
			type = tactical_bomber
			model = 4
			id = { type = 30018 id = 377 }
			name = "4th Air Wing"
		}
	}
	airunit = {
		id = { type = 30018 id = 378 }
		name = "Bomber Group 2"
		location = 1552
		base = 1552
		division = {
			type = tactical_bomber
			model = 4
			id = { type = 30018 id = 379 }
			name = "5th Air Wing"
		}
		division = {
			type = tactical_bomber
			model = 4
			id = { type = 30018 id = 380 }
			name = "6th Air Wing"
		}
		division = {
			type = tactical_bomber
			model = 4
			id = { type = 30018 id = 381 }
			name = "7th Air Wing"
		}
		division = {
			type = tactical_bomber
			model = 4
			id = { type = 30018 id = 382 }
			name = "8th Air Wing"
		}
	}
	airunit = {
		id = { type = 30018 id = 383 }
		name = "Fighter Group 1"
		location = 1552
		base = 1552
		division = {
			type = interceptor
			model = 6
			id = { type = 30018 id = 384 }
			name = "9th Air Wing"
		}
		division = {
			type = interceptor
			model = 6
			id = { type = 30018 id = 385 }
			name = "10th Air Wing"
		}
		division = {
			type = interceptor
			model = 6
			id = { type = 30018 id = 386 }
			name = "11th Air Wing"
		}
		division = {
			type = interceptor
			model = 6
			id = { type = 30018 id = 387 }
			name = "12th Air Wing"
		}
	}
	airunit = {
		id = { type = 30018 id = 388 }
		name = "Fighter Group 2"
		location = 1552
		base = 1552
		division = {
			type = interceptor
			model = 6
			id = { type = 30018 id = 389 }
			name = "13th Air Wing"
		}
		division = {
			type = interceptor
			model = 6
			id = { type = 30018 id = 390 }
			name = "14th Air Wing"
		}
		division = {
			type = interceptor
			model = 6
			id = { type = 30018 id = 391 }
			name = "15th Air Wing"
		}
		division = {
			type = interceptor
			model = 6
			id = { type = 30018 id = 392 }
			name = "16th Air Wing"
		}
	}
}
